# Generated by Django 2.0.5 on 2018-06-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('passive_view', 'passive_view'), ('positive_view', 'positive_view'), ('passive_send_msg', 'passive_send_msg'), ('positive_send_msg', 'positive_send_msg'))},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=5),
        ),
    ]
